#############################################################################
# Makefile for building: Autocomplete
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Autocomplete.pro
# Template: app
# Command: /software/common64/qt/bin/qmake -o Makefile Autocomplete.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/software/common64/qt-5.5.0/include -I/software/common64/qt-5.5.0/include/QtWidgets -I/software/common64/qt-5.5.0/include/QtGui -I/software/common64/qt-5.5.0/include/QtCore -I. -I. -I/software/common64/qt-5.5.0/mkspecs/linux-g++
QMAKE         = /software/common64/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Autocomplete1.0.0
DISTDIR = /home/linux/ieng6/cs100w/cs100wac/pa2/.tmp/Autocomplete1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/software/common64/qt-5.5.0/lib
LIBS          = $(SUBLIBS) -L/software/common64/qt-5.5.0/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		wordlist.cpp \
		mylineedit.cpp \
		../DictionaryBST.cpp \
		../DictionaryHashTable.cpp \
		../DictionaryTrie.cpp \
		../util.cpp 
OBJECTS       = main.o \
		mainwindow.o \
		wordlist.o \
		mylineedit.o \
		DictionaryBST.o \
		DictionaryHashTable.o \
		DictionaryTrie.o \
		util.o
DIST          = /software/common64/qt-5.5.0/mkspecs/features/spec_pre.prf \
		/software/common64/qt-5.5.0/mkspecs/common/unix.conf \
		/software/common64/qt-5.5.0/mkspecs/common/linux.conf \
		/software/common64/qt-5.5.0/mkspecs/common/sanitize.conf \
		/software/common64/qt-5.5.0/mkspecs/common/gcc-base.conf \
		/software/common64/qt-5.5.0/mkspecs/common/gcc-base-unix.conf \
		/software/common64/qt-5.5.0/mkspecs/common/g++-base.conf \
		/software/common64/qt-5.5.0/mkspecs/common/g++-unix.conf \
		/software/common64/qt-5.5.0/mkspecs/qconfig.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/software/common64/qt-5.5.0/mkspecs/features/qt_functions.prf \
		/software/common64/qt-5.5.0/mkspecs/features/qt_config.prf \
		/software/common64/qt-5.5.0/mkspecs/linux-g++/qmake.conf \
		/software/common64/qt-5.5.0/mkspecs/features/spec_post.prf \
		/software/common64/qt-5.5.0/mkspecs/features/exclusive_builds.prf \
		/software/common64/qt-5.5.0/mkspecs/features/default_pre.prf \
		/software/common64/qt-5.5.0/mkspecs/features/resolve_config.prf \
		/software/common64/qt-5.5.0/mkspecs/features/default_post.prf \
		/software/common64/qt-5.5.0/mkspecs/features/c++11.prf \
		/software/common64/qt-5.5.0/mkspecs/features/warn_on.prf \
		/software/common64/qt-5.5.0/mkspecs/features/qt.prf \
		/software/common64/qt-5.5.0/mkspecs/features/resources.prf \
		/software/common64/qt-5.5.0/mkspecs/features/moc.prf \
		/software/common64/qt-5.5.0/mkspecs/features/unix/opengl.prf \
		/software/common64/qt-5.5.0/mkspecs/features/uic.prf \
		/software/common64/qt-5.5.0/mkspecs/features/unix/thread.prf \
		/software/common64/qt-5.5.0/mkspecs/features/testcase_targets.prf \
		/software/common64/qt-5.5.0/mkspecs/features/exceptions.prf \
		/software/common64/qt-5.5.0/mkspecs/features/yacc.prf \
		/software/common64/qt-5.5.0/mkspecs/features/lex.prf \
		Autocomplete.pro mainwindow.h \
		wordlist.h \
		mylineedit.h \
		../DictionaryBST.h \
		../DictionaryHashTable.h \
		../DictionaryTrie.h \
		../util.h main.cpp \
		mainwindow.cpp \
		wordlist.cpp \
		mylineedit.cpp \
		../DictionaryBST.cpp \
		../DictionaryHashTable.cpp \
		../DictionaryTrie.cpp \
		../util.cpp
QMAKE_TARGET  = Autocomplete
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Autocomplete


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Autocomplete.pro /software/common64/qt-5.5.0/mkspecs/linux-g++/qmake.conf /software/common64/qt-5.5.0/mkspecs/features/spec_pre.prf \
		/software/common64/qt-5.5.0/mkspecs/common/unix.conf \
		/software/common64/qt-5.5.0/mkspecs/common/linux.conf \
		/software/common64/qt-5.5.0/mkspecs/common/sanitize.conf \
		/software/common64/qt-5.5.0/mkspecs/common/gcc-base.conf \
		/software/common64/qt-5.5.0/mkspecs/common/gcc-base-unix.conf \
		/software/common64/qt-5.5.0/mkspecs/common/g++-base.conf \
		/software/common64/qt-5.5.0/mkspecs/common/g++-unix.conf \
		/software/common64/qt-5.5.0/mkspecs/qconfig.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/software/common64/qt-5.5.0/mkspecs/features/qt_functions.prf \
		/software/common64/qt-5.5.0/mkspecs/features/qt_config.prf \
		/software/common64/qt-5.5.0/mkspecs/linux-g++/qmake.conf \
		/software/common64/qt-5.5.0/mkspecs/features/spec_post.prf \
		/software/common64/qt-5.5.0/mkspecs/features/exclusive_builds.prf \
		/software/common64/qt-5.5.0/mkspecs/features/default_pre.prf \
		/software/common64/qt-5.5.0/mkspecs/features/resolve_config.prf \
		/software/common64/qt-5.5.0/mkspecs/features/default_post.prf \
		/software/common64/qt-5.5.0/mkspecs/features/c++11.prf \
		/software/common64/qt-5.5.0/mkspecs/features/warn_on.prf \
		/software/common64/qt-5.5.0/mkspecs/features/qt.prf \
		/software/common64/qt-5.5.0/mkspecs/features/resources.prf \
		/software/common64/qt-5.5.0/mkspecs/features/moc.prf \
		/software/common64/qt-5.5.0/mkspecs/features/unix/opengl.prf \
		/software/common64/qt-5.5.0/mkspecs/features/uic.prf \
		/software/common64/qt-5.5.0/mkspecs/features/unix/thread.prf \
		/software/common64/qt-5.5.0/mkspecs/features/testcase_targets.prf \
		/software/common64/qt-5.5.0/mkspecs/features/exceptions.prf \
		/software/common64/qt-5.5.0/mkspecs/features/yacc.prf \
		/software/common64/qt-5.5.0/mkspecs/features/lex.prf \
		Autocomplete.pro \
		/software/common64/qt-5.5.0/lib/libQt5Widgets.prl \
		/software/common64/qt-5.5.0/lib/libQt5Gui.prl \
		/software/common64/qt-5.5.0/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Autocomplete.pro
/software/common64/qt-5.5.0/mkspecs/features/spec_pre.prf:
/software/common64/qt-5.5.0/mkspecs/common/unix.conf:
/software/common64/qt-5.5.0/mkspecs/common/linux.conf:
/software/common64/qt-5.5.0/mkspecs/common/sanitize.conf:
/software/common64/qt-5.5.0/mkspecs/common/gcc-base.conf:
/software/common64/qt-5.5.0/mkspecs/common/gcc-base-unix.conf:
/software/common64/qt-5.5.0/mkspecs/common/g++-base.conf:
/software/common64/qt-5.5.0/mkspecs/common/g++-unix.conf:
/software/common64/qt-5.5.0/mkspecs/qconfig.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_3drenderer_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_clucene_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_core_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_dbus_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_declarative_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designer_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_enginio_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_gui_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_help_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_location_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_network_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_nfc_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_opengl_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_positioning_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qml_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quick_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_script_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sensors_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_serialport_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_sql_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_svg_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_testlib_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uiplugin.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_uitools_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_websockets_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_widgets_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_x11extras_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xml_private.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/software/common64/qt-5.5.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/software/common64/qt-5.5.0/mkspecs/features/qt_functions.prf:
/software/common64/qt-5.5.0/mkspecs/features/qt_config.prf:
/software/common64/qt-5.5.0/mkspecs/linux-g++/qmake.conf:
/software/common64/qt-5.5.0/mkspecs/features/spec_post.prf:
/software/common64/qt-5.5.0/mkspecs/features/exclusive_builds.prf:
/software/common64/qt-5.5.0/mkspecs/features/default_pre.prf:
/software/common64/qt-5.5.0/mkspecs/features/resolve_config.prf:
/software/common64/qt-5.5.0/mkspecs/features/default_post.prf:
/software/common64/qt-5.5.0/mkspecs/features/c++11.prf:
/software/common64/qt-5.5.0/mkspecs/features/warn_on.prf:
/software/common64/qt-5.5.0/mkspecs/features/qt.prf:
/software/common64/qt-5.5.0/mkspecs/features/resources.prf:
/software/common64/qt-5.5.0/mkspecs/features/moc.prf:
/software/common64/qt-5.5.0/mkspecs/features/unix/opengl.prf:
/software/common64/qt-5.5.0/mkspecs/features/uic.prf:
/software/common64/qt-5.5.0/mkspecs/features/unix/thread.prf:
/software/common64/qt-5.5.0/mkspecs/features/testcase_targets.prf:
/software/common64/qt-5.5.0/mkspecs/features/exceptions.prf:
/software/common64/qt-5.5.0/mkspecs/features/yacc.prf:
/software/common64/qt-5.5.0/mkspecs/features/lex.prf:
Autocomplete.pro:
/software/common64/qt-5.5.0/lib/libQt5Widgets.prl:
/software/common64/qt-5.5.0/lib/libQt5Gui.prl:
/software/common64/qt-5.5.0/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Autocomplete.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h wordlist.h mylineedit.h ../DictionaryBST.h ../DictionaryHashTable.h ../DictionaryTrie.h ../util.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp wordlist.cpp mylineedit.cpp ../DictionaryBST.cpp ../DictionaryHashTable.cpp ../DictionaryTrie.cpp ../util.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/software/common64/qt-5.5.0/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_uic_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

wordlist.o: wordlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wordlist.o wordlist.cpp

mylineedit.o: mylineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylineedit.o mylineedit.cpp

DictionaryBST.o: ../DictionaryBST.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DictionaryBST.o ../DictionaryBST.cpp

DictionaryHashTable.o: ../DictionaryHashTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DictionaryHashTable.o ../DictionaryHashTable.cpp

DictionaryTrie.o: ../DictionaryTrie.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DictionaryTrie.o ../DictionaryTrie.cpp

util.o: ../util.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o ../util.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

